sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tGvV86xN9RCWYFECKrT
    access-key-secret: qYA5IkfOSMzORIdQRCBeFHwa739by4
    bucket-name: sky-takeout-pro1013
